"""add profile, verification, and mfa fields to users

Revision ID: 66222e8d1ff9
Revises: 16f592b88e9c
Create Date: 2026-09-22 22:30:47.720032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66222e8d1ff9'
down_revision: Union[str, Sequence[str], None] = '16f592b88e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=280), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('facebook_url', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('instagram_url', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('x_url', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('website_url', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('verification_code_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'verification_code_expires_at')
    op.drop_column('users', 'verification_code_hash')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'website_url')
    op.drop_column('users', 'x_url')
    op.drop_column('users', 'instagram_url')
    op.drop_column('users', 'facebook_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
