"""add lab launch tracking fields

Revision ID: 9a9fd5632c80
Revises: 8bf1410d6184
Create Date: 2026-09-23 16:59:10.134594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9fd5632c80'
down_revision: Union[str, Sequence[str], None] = '8bf1410d6184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_sessions', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lab_sessions', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('lab_sessions', sa.Column('connection_info', sa.String(length=500), nullable=True))
    op.add_column('labs', sa.Column('summary', sa.String(length=500), nullable=True))
    op.add_column('labs', sa.Column('published', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'published')
    op.drop_column('labs', 'summary')
    op.drop_column('lab_sessions', 'connection_info')
    op.drop_column('lab_sessions', 'port')
    op.drop_column('lab_sessions', 'last_active_at')
    # ### end Alembic commands ###
